import test from "node:test";
import assert from "node:assert/strict";
import {
  Action,
  Card,
  Rank,
  Rules,
  ShoeSession,
  answerInsurance,
  createDeck,
  createShoe,
  getActiveScenario,
  handValue,
  legalActions,
  makeScenario,
  playAction,
  recommend,
  seededRandom,
  startRound,
} from "../src/engine";

// Independent fixture matrix checked against Michael Shackleford's published
// 4–8 deck text and chart, including DAS and late surrender, on 2026-09-20:
// https://wizardofodds.com/games/blackjack/strategy/4-decks/
// https://wizardofodds.com/games/blackjack/surrender/
// Columns are dealer 2,3,4,5,6,7,8,9,10,A. These are fixed expected answers;
// no expected cell is generated by the strategy evaluator under test.
const REFERENCE_ROWS: {
  id: string;
  ranks: Rank[];
  s17: string;
  h17: string;
}[] = [
  { id: "H5", ranks: ["2", "3"], s17: "HHHHHHHHHH", h17: "HHHHHHHHHH" },
  { id: "H6", ranks: ["2", "4"], s17: "HHHHHHHHHH", h17: "HHHHHHHHHH" },
  { id: "H7", ranks: ["3", "4"], s17: "HHHHHHHHHH", h17: "HHHHHHHHHH" },
  { id: "H8", ranks: ["3", "5"], s17: "HHHHHHHHHH", h17: "HHHHHHHHHH" },
  { id: "H9", ranks: ["4", "5"], s17: "HDDDDHHHHH", h17: "HDDDDHHHHH" },
  { id: "H10", ranks: ["4", "6"], s17: "DDDDDDDDHH", h17: "DDDDDDDDHH" },
  { id: "H11", ranks: ["5", "6"], s17: "DDDDDDDDDH", h17: "DDDDDDDDDD" },
  { id: "H12", ranks: ["10", "2"], s17: "HHSSSHHHHH", h17: "HHSSSHHHHH" },
  { id: "H13", ranks: ["10", "3"], s17: "SSSSSHHHHH", h17: "SSSSSHHHHH" },
  { id: "H14", ranks: ["10", "4"], s17: "SSSSSHHHHH", h17: "SSSSSHHHHH" },
  { id: "H15", ranks: ["10", "5"], s17: "SSSSSHHHRH", h17: "SSSSSHHHRR" },
  { id: "H16", ranks: ["10", "6"], s17: "SSSSSHHRRR", h17: "SSSSSHHRRR" },
  { id: "H17", ranks: ["10", "7"], s17: "SSSSSSSSSS", h17: "SSSSSSSSSR" },
  { id: "H18", ranks: ["10", "8"], s17: "SSSSSSSSSS", h17: "SSSSSSSSSS" },
  { id: "H19", ranks: ["10", "9"], s17: "SSSSSSSSSS", h17: "SSSSSSSSSS" },
  { id: "H20", ranks: ["10", "K"], s17: "SSSSSSSSSS", h17: "SSSSSSSSSS" },
  { id: "S13", ranks: ["A", "2"], s17: "HHHDDHHHHH", h17: "HHHDDHHHHH" },
  { id: "S14", ranks: ["A", "3"], s17: "HHHDDHHHHH", h17: "HHHDDHHHHH" },
  { id: "S15", ranks: ["A", "4"], s17: "HHDDDHHHHH", h17: "HHDDDHHHHH" },
  { id: "S16", ranks: ["A", "5"], s17: "HHDDDHHHHH", h17: "HHDDDHHHHH" },
  { id: "S17", ranks: ["A", "6"], s17: "HDDDDHHHHH", h17: "HDDDDHHHHH" },
  { id: "S18", ranks: ["A", "7"], s17: "SDDDDSSHHH", h17: "DDDDDSSHHH" },
  { id: "S19", ranks: ["A", "8"], s17: "SSSSSSSSSS", h17: "SSSSDSSSSS" },
  { id: "S20", ranks: ["A", "9"], s17: "SSSSSSSSSS", h17: "SSSSSSSSSS" },
  { id: "P2", ranks: ["2", "2"], s17: "PPPPPPHHHH", h17: "PPPPPPHHHH" },
  { id: "P3", ranks: ["3", "3"], s17: "PPPPPPHHHH", h17: "PPPPPPHHHH" },
  { id: "P4", ranks: ["4", "4"], s17: "HHHPPHHHHH", h17: "HHHPPHHHHH" },
  { id: "P5", ranks: ["5", "5"], s17: "DDDDDDDDHH", h17: "DDDDDDDDHH" },
  { id: "P6", ranks: ["6", "6"], s17: "PPPPPHHHHH", h17: "PPPPPHHHHH" },
  { id: "P7", ranks: ["7", "7"], s17: "PPPPPPHHHH", h17: "PPPPPPHHHH" },
  { id: "P8", ranks: ["8", "8"], s17: "PPPPPPPPPP", h17: "PPPPPPPPPR" },
  { id: "P9", ranks: ["9", "9"], s17: "PPPPPSPPSS", h17: "PPPPPSPPSS" },
  { id: "P10", ranks: ["K", "Q"], s17: "SSSSSSSSSS", h17: "SSSSSSSSSS" },
  { id: "PA", ranks: ["A", "A"], s17: "PPPPPPPPPP", h17: "PPPPPPPPPP" },
];
const UP_CARDS: Rank[] = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "A"];
const ACTION_CODES: Record<string, Action> = {
  H: "hit",
  S: "stand",
  D: "double",
  P: "split",
  R: "surrender",
};

test("QA: all 1,360 source-matrix cells match four supported table configurations", () => {
  let checked = 0;
  for (const hitSoft17 of [false, true]) {
    for (const surrender of [false, true]) {
      const rules = { hitSoft17, surrender };
      for (const row of REFERENCE_ROWS) {
        const codes = hitSoft17 ? row.h17 : row.s17;
        assert.equal(codes.length, 10, `${row.id} fixture width`);
        for (let col = 0; col < UP_CARDS.length; col++) {
          let expected = ACTION_CODES[codes[col]];
          if (!surrender && expected === "surrender") {
            // Explicit surrender fallback cells: H17 stands; paired eights split;
            // the hard 15/16 cells hit. These are source-chart fallbacks.
            expected =
              row.id === "H17" ? "stand" : row.id === "P8" ? "split" : "hit";
          }
          const actual = recommend(
            makeScenario(row.ranks, UP_CARDS[col]),
            rules,
          ).action;
          assert.equal(
            actual,
            expected,
            `${row.id} vs ${UP_CARDS[col]}, ${hitSoft17 ? "H17" : "S17"}, surrender ${surrender}`,
          );
          checked++;
        }
      }
    }
  }
  assert.equal(checked, 1360);
});

/** Enumerates all ace assignments rather than using the engine's downgrade loop. */
function independentValue(cards: readonly Card[]) {
  const nonAce = cards
    .filter((card) => card.rank !== "A")
    .reduce(
      (total, card) =>
        total +
        (["10", "J", "Q", "K"].includes(card.rank) ? 10 : Number(card.rank)),
      0,
    );
  const aces = cards.filter((card) => card.rank === "A").length;
  const possible = Array.from({ length: aces + 1 }, (_, elevated) => ({
    total: nonAce + aces + elevated * 10,
    soft: elevated > 0,
  }));
  const legal = possible.filter((value) => value.total <= 21);
  const best = legal.length ? legal[legal.length - 1] : possible[0];
  return { ...best, blackjack: cards.length === 2 && best.total === 21 };
}

function countPoint(card: Card): number {
  return ["2", "3", "4", "5", "6"].includes(card.rank)
    ? 1
    : ["10", "J", "Q", "K", "A"].includes(card.rank)
      ? -1
      : 0;
}

function rig(
  ranks: Rank[],
  rules: Rules = { hitSoft17: false, surrender: true },
): ShoeSession {
  const session = createShoe(7123, rules);
  const rest = [...session.cards];
  const front = ranks.map(
    (rank) =>
      rest.splice(
        rest.findIndex((card) => card.rank === rank),
        1,
      )[0],
  );
  return { ...session, cards: [...front, ...rest] };
}

test("QA: ace values agree with independent exhaustive assignments", () => {
  for (let seed = 0; seed < 500; seed++) {
    const cards = createDeck(seed, 6);
    for (let count = 2; count <= 12; count++) {
      const selected = cards.slice(0, count);
      assert.deepEqual(
        handValue(selected),
        independentValue(selected),
        `seed ${seed}, ${count} cards`,
      );
    }
  }
});

test("QA: insurance plus surrender or double settles the exact combined fractional wager", () => {
  let surrender = answerInsurance(
    startRound(rig(["10", "A", "6", "6"]), 2.5),
    true,
  );
  surrender = playAction(surrender, "surrender");
  assert.equal(surrender.round?.insuranceProfit, -1.25);
  assert.equal(surrender.round?.hands[0].profit, -1.25);
  assert.equal(surrender.round?.profit, -2.5);
  assert.equal(surrender.bankroll, 97.5);

  let doubled = answerInsurance(
    startRound(
      rig(["5", "A", "6", "5", "10", "2"], {
        hitSoft17: true,
        surrender: true,
      }),
      2.5,
    ),
    true,
  );
  doubled = playAction(doubled, "double");
  assert.equal(doubled.round?.hands[0].bet, 5);
  assert.equal(doubled.round?.hands[0].profit, 5);
  assert.equal(doubled.round?.insuranceProfit, -1.25);
  assert.equal(doubled.round?.profit, 3.75);
  assert.equal(doubled.bankroll, 103.75);
});

test("QA: non-ace split 21 pushes dealer 21 and multi-ace soft 17 follows the table rule", () => {
  const split = playAction(
    startRound(rig(["K", "6", "Q", "10", "A", "A", "5"])),
    "split",
  );
  assert.equal(split.round?.phase, "complete");
  assert.deepEqual(
    split.round?.hands.map((hand) => hand.result),
    ["push", "push"],
  );
  assert.equal(split.round?.profit, 0);
  for (const hitSoft17 of [false, true]) {
    let session = answerInsurance(
      startRound(
        rig(["10", "A", "8", "A", "A", "4", "10"], {
          hitSoft17,
          surrender: true,
        }),
      ),
      false,
    );
    session = playAction(session, "stand");
    assert.equal(session.round?.dealer.length, hitSoft17 ? 5 : 4);
    assert.equal(handValue(session.round!.dealer).total, 17);
    assert.equal(handValue(session.round!.dealer).soft, !hitSoft17);
    assert.equal(session.round?.profit, 1);
  }
});

test("QA: terminal split cards remain in round history while the next hand is active", () => {
  let doubled = playAction(
    startRound(rig(["8", "6", "8", "10", "3", "K", "2"])),
    "split",
  );
  const previouslySeen = new Set(doubled.seenIds);
  doubled = playAction(doubled, "double");
  assert.equal(doubled.round?.phase, "playing");
  assert.equal(doubled.round?.activeHand, 1);
  const newlySeen = doubled.cards.filter(
    (card) => doubled.seenIds.includes(card.id) && !previouslySeen.has(card.id),
  );
  assert.deepEqual(
    newlySeen.map((card) => card.rank),
    ["K", "2"],
  );
  assert.deepEqual(
    getActiveScenario(doubled)?.cards.map((card) => card.rank),
    ["8", "2"],
  );
  assert.equal(doubled.round?.hands[0].cards.at(-1)?.rank, "K");

  // If a UI renders only getActiveScenario(), the king above is not visible.
  // All player hands plus the upcard expose exactly the engine's public cards.
  const publicRoundCards = [
    doubled.round!.dealer[0],
    ...doubled.round!.hands.flatMap((hand) => hand.cards),
  ];
  assert.deepEqual(
    new Set(publicRoundCards.map((card) => card.id)),
    new Set(doubled.seenIds),
  );
  assert.ok(
    !publicRoundCards.some((card) => card.id === doubled.round!.dealer[1].id),
  );

  const automatic = playAction(
    startRound(rig(["K", "6", "Q", "10", "A", "2"])),
    "split",
  );
  assert.equal(automatic.round?.phase, "playing");
  assert.equal(automatic.round?.hands[0].status, "stood");
  assert.deepEqual(
    automatic.round?.hands[0].cards.map((card) => card.rank),
    ["K", "A"],
  );
  assert.deepEqual(
    getActiveScenario(automatic)?.cards.map((card) => card.rank),
    ["Q", "2"],
  );
  assert.equal(
    automatic.seenIds.length,
    5,
    "both replacement cards count before the sibling decision",
  );
});

test("QA: 3,200 randomized legal-action rounds preserve accounting, visibility, persistence, and shuffles", () => {
  const actionsSeen = new Set<Action>();
  let insuranceDecisions = 0;
  let persistedTransitions = 0;
  for (let seed = 0; seed < 8; seed++) {
    for (const hitSoft17 of [false, true]) {
      for (const surrender of [false, true]) {
        const random = seededRandom(
          seed * 101 + Number(hitSoft17) * 17 + Number(surrender) * 31,
        );
        const rules = { hitSoft17, surrender };
        let session = createShoe(
          seed + 923,
          rules,
          [0.25, 0.75, 0.85][seed % 3],
        );
        let cumulativeProfit = 0;
        for (let round = 0; round < 100; round++) {
          const bet = [0.5, 1, 2.5, 8, 100][Math.floor(random() * 5)];
          const surrenderedIds = new Set<string>();
          session = startRound(session, bet, round);
          const insuranceTaken =
            session.round?.phase === "insurance" && random() < 0.5;
          if (session.round?.phase === "insurance") {
            assert.equal(
              getActiveScenario(session),
              null,
              "no playing action before insurance/peek resolves",
            );
            assert.equal(
              session.seenIds.length,
              session.nextCard - 1,
              "hole remains hidden before peek",
            );
            session = answerInsurance(
              session,
              insuranceTaken,
              session.round.id,
            );
            insuranceDecisions++;
          }
          for (
            let decision = 0;
            session.round?.phase === "playing";
            decision++
          ) {
            assert.ok(
              decision < 80,
              "all legal-action sequences must terminate",
            );
            const scenario = getActiveScenario(session)!;
            assert.equal(session.seenIds.length, session.nextCard - 1);
            assert.equal(
              session.runningCount,
              session.cards
                .filter((card) => session.seenIds.includes(card.id))
                .reduce((sum, card) => sum + countPoint(card), 0),
            );
            const legal = legalActions(scenario, rules);
            const action = legal[Math.floor(random() * legal.length)];
            actionsSeen.add(action);
            if (action === "surrender")
              surrenderedIds.add(
                session.round!.hands[session.round!.activeHand].id,
              );
            const previous = session;
            session = playAction(session, action, scenario.id);
            assert.equal(
              playAction(session, action, scenario.id),
              session,
              "old decision ID is idempotent",
            );
            if (decision === 0 && round % 10 === 0) {
              const restored: ShoeSession = JSON.parse(
                JSON.stringify(previous),
              );
              assert.deepEqual(
                playAction(restored, action, scenario.id),
                session,
                "saved in-progress shoe resumes identically",
              );
              persistedTransitions++;
            }
          }
          const completed = session.round!;
          const dealer = independentValue(completed.dealer);
          let expectedProfit = insuranceTaken
            ? dealer.blackjack
              ? bet
              : -bet / 2
            : 0;
          assert.equal(completed.insuranceBet, insuranceTaken ? bet / 2 : 0);
          assert.equal(completed.insuranceProfit, expectedProfit);
          for (const hand of completed.hands) {
            const player = independentValue(hand.cards);
            const natural = player.blackjack && !hand.fromSplit;
            const expectedHand = surrenderedIds.has(hand.id)
              ? -hand.bet / 2
              : player.total > 21
                ? -hand.bet
                : dealer.blackjack
                  ? natural
                    ? 0
                    : -hand.bet
                  : natural
                    ? hand.bet * 1.5
                    : dealer.total > 21 || player.total > dealer.total
                      ? hand.bet
                      : player.total === dealer.total
                        ? 0
                        : -hand.bet;
            assert.equal(hand.profit, expectedHand);
            assert.equal(hand.status, "settled");
            expectedProfit += expectedHand;
          }
          cumulativeProfit += expectedProfit;
          assert.equal(completed.profit, expectedProfit);
          assert.equal(session.bankroll, 100 + cumulativeProfit);
          assert.equal(session.rounds, round + 1);
          assert.equal(session.seenIds.length, session.nextCard);
          assert.equal(new Set(session.seenIds).size, session.nextCard);
          assert.equal(
            session.runningCount,
            session.cards
              .slice(0, session.nextCard)
              .reduce((sum, card) => sum + countPoint(card), 0),
          );
          assert.deepEqual(
            session.discarded,
            session.cards.slice(0, session.nextCard),
          );
          assert.equal(getActiveScenario(session), null);
          assert.ok(session.nextCard <= 312);
          assert.ok(completed.hands.length <= 4);
        }
        assert.ok(
          session.shuffleNumber >= 2,
          "each run crosses at least one shuffle boundary",
        );
      }
    }
  }
  assert.equal(actionsSeen.size, 5);
  assert.ok(insuranceDecisions > 100);
  assert.ok(persistedTransitions > 100);
});
