import test from "node:test";
import assert from "node:assert/strict";
import {
  Action,
  Card,
  DEFAULT_RULES,
  DEVIATION_RULES,
  Rank,
  Rules,
  ShoeSession,
  answerInsurance,
  category,
  createDeck,
  createShoe,
  decksRemaining,
  generateScenario,
  getActiveScenario,
  handValue,
  hiLo,
  insuranceRecommendation,
  legalActions,
  makeCard,
  makeScenario,
  playAction,
  rawTrueCount,
  recommend,
  seededRandom,
  startRound,
  trueCount,
  validateScenario,
  visibleCards,
} from "../src/engine";

const hand = (ranks: Rank[]) =>
  ranks.map((rank, index) => makeCard(rank, `test-${index}`));
const strategy = (ranks: Rank[], dealer: Rank, rules = DEFAULT_RULES) =>
  recommend(makeScenario(ranks, dealer), rules).action;

/** Reorder real physical cards so edge cases have a known deal, without changing the shoe composition. */
function rig(ranks: Rank[], rules: Rules = DEFAULT_RULES): ShoeSession {
  const session = createShoe(931, rules);
  const rest = [...session.cards];
  const front: Card[] = ranks.map((rank) => {
    const index = rest.findIndex((card) => card.rank === rank);
    assert.ok(index >= 0);
    return rest.splice(index, 1)[0];
  });
  return { ...session, cards: [...front, ...rest] };
}

test("aces downgrade individually; two-card 21 is distinguished from multi-card 21", () => {
  assert.deepEqual(handValue(hand(["A", "A", "9"])), {
    total: 21,
    soft: true,
    blackjack: false,
  });
  assert.deepEqual(handValue(hand(["A", "6", "10"])), {
    total: 17,
    soft: false,
    blackjack: false,
  });
  assert.deepEqual(handValue(hand(["A", "A", "9", "K"])), {
    total: 21,
    soft: false,
    blackjack: false,
  });
  assert.deepEqual(handValue(hand(["A", "K"])), {
    total: 21,
    soft: true,
    blackjack: true,
  });
  assert.equal(handValue(hand(["K", "Q", "2"])).total, 22);
});

test("independent basic strategy reference cases match six-deck S17 DAS chart", () => {
  // Fixed expected answers transcribed from Wizard of Odds 4–8 deck strategy (not generated by the implementation).
  const cases: [Rank[], Rank, Action][] = [
    [["10", "2"], "3", "hit"],
    [["10", "2"], "4", "stand"],
    [["10", "3"], "2", "stand"],
    [["10", "6"], "7", "hit"],
    [["10", "7"], "A", "stand"],
    [["4", "5"], "2", "hit"],
    [["4", "5"], "3", "double"],
    [["4", "6"], "9", "double"],
    [["4", "6"], "10", "hit"],
    [["5", "6"], "10", "double"],
    [["5", "6"], "A", "hit"],
    [["A", "2"], "4", "hit"],
    [["A", "2"], "5", "double"],
    [["A", "4"], "4", "double"],
    [["A", "6"], "3", "double"],
    [["A", "7"], "2", "stand"],
    [["A", "7"], "6", "double"],
    [["A", "7"], "8", "stand"],
    [["A", "7"], "9", "hit"],
    [["A", "8"], "6", "stand"],
    [["2", "2"], "2", "split"],
    [["3", "3"], "7", "split"],
    [["4", "4"], "4", "hit"],
    [["4", "4"], "5", "split"],
    [["5", "5"], "6", "double"],
    [["6", "6"], "2", "split"],
    [["7", "7"], "8", "hit"],
    [["8", "8"], "10", "split"],
    [["8", "8"], "A", "split"],
    [["9", "9"], "7", "stand"],
    [["9", "9"], "8", "split"],
    [["9", "9"], "10", "stand"],
    [["10", "10"], "6", "stand"],
    [["A", "A"], "A", "split"],
    [["10", "5"], "10", "surrender"],
    [["10", "6"], "9", "surrender"],
    [["10", "6"], "A", "surrender"],
    [["10", "5"], "A", "hit"],
  ];
  for (const [ranks, dealer, expected] of cases)
    assert.equal(
      strategy(ranks, dealer),
      expected,
      `${ranks.join("+")} vs ${dealer}`,
    );
});

test("H17 changes doubling and late surrender, including 8+8 versus ace", () => {
  const h17 = { hitSoft17: true, surrender: true };
  assert.equal(strategy(["5", "6"], "A", h17), "double");
  assert.equal(strategy(["A", "7"], "2", h17), "double");
  assert.equal(strategy(["A", "8"], "6", h17), "double");
  for (const ranks of [
    ["10", "5"],
    ["8", "8"],
    ["10", "7"],
  ] as Rank[][])
    assert.equal(strategy(ranks, "A", h17), "surrender");
  assert.equal(
    strategy(["8", "8"], "A", { ...h17, surrender: false }),
    "split",
  );
  assert.equal(
    strategy(["10", "7"], "A", { ...h17, surrender: false }),
    "stand",
  );
});

test("legal fallbacks preserve soft 18/19 when double is unavailable", () => {
  assert.equal(recommend(makeScenario(["A", "2", "5"], "6")).action, "stand");
  assert.equal(
    recommend(makeScenario(["A", "3", "5"], "6"), {
      hitSoft17: true,
      surrender: true,
    }).action,
    "stand",
  );
  assert.equal(recommend(makeScenario(["2", "3", "6"], "6")).action, "hit");
  assert.equal(
    recommend(
      makeScenario(["8", "8"], "10", { fromSplit: true, handsCount: 4 }),
    ).action,
    "hit",
  );
});

test("splitting, doubling, surrender and split aces obey eligibility", () => {
  const initial = makeScenario(["8", "8"], "6");
  assert.deepEqual(legalActions(initial), [
    "hit",
    "stand",
    "double",
    "split",
    "surrender",
  ]);
  assert.deepEqual(legalActions(makeScenario(["4", "4", "3"], "6")), [
    "hit",
    "stand",
  ]);
  assert.ok(
    !legalActions({ ...initial, fromSplit: true, handsCount: 2 }).includes(
      "surrender",
    ),
  );
  assert.ok(!legalActions({ ...initial, handsCount: 4 }).includes("split"));
  assert.deepEqual(
    legalActions(
      makeScenario(["A", "8"], "6", {
        fromSplit: true,
        splitAces: true,
        handsCount: 2,
      }),
    ),
    ["stand"],
  );
  assert.ok(legalActions(makeScenario(["K", "Q"], "6")).includes("split"));
  assert.equal(category(makeScenario(["A", "A", "4"], "6")), "soft");
});

test("Hi-Lo is balanced and true count floors negative values consistently", () => {
  assert.deepEqual(
    ["2", "6", "7", "9", "10", "J", "A"].map((rank) =>
      hiLo(makeCard(rank as Rank)),
    ),
    [1, 1, 0, 0, -1, -1, -1],
  );
  assert.equal(
    createDeck(42).reduce((sum, card) => sum + hiLo(card), 0),
    0,
  );
  assert.equal(trueCount(7, 4), 1);
  assert.equal(rawTrueCount(7, 4), 1.75);
  assert.equal(trueCount(-1, 2), -1);
  assert.equal(trueCount(-5, 2), -3);
  assert.throws(() => trueCount(1, 0), RangeError);
});

test("deviation boundary tests use a small explicit S17 no-surrender subset", () => {
  const below = makeScenario(["10", "2"], "3", { trueCount: 1 });
  const at = { ...below, trueCount: 2 };
  assert.equal(recommend(below, DEVIATION_RULES, true).action, "hit");
  assert.equal(recommend(at, DEVIATION_RULES, true).action, "stand");
  assert.equal(recommend(at, DEVIATION_RULES, false).action, "hit");
  assert.equal(recommend(at, DEFAULT_RULES, true).action, "hit");
  assert.equal(
    recommend(at, { hitSoft17: true, surrender: false }, true).action,
    "hit",
  );
  assert.equal(
    recommend(
      makeScenario(["10", "6"], "10", { trueCount: -1 }),
      DEVIATION_RULES,
      true,
    ).action,
    "hit",
  );
  assert.equal(
    recommend(
      makeScenario(["10", "6"], "10", { trueCount: 0 }),
      DEVIATION_RULES,
      true,
    ).action,
    "stand",
  );
  assert.equal(
    recommend(
      makeScenario(["8", "8"], "10", { trueCount: 6 }),
      DEVIATION_RULES,
      true,
    ).action,
    "split",
  );
  assert.equal(
    recommend(
      makeScenario(["4", "6"], "10", { trueCount: 4 }),
      DEVIATION_RULES,
      true,
    ).action,
    "double",
  );
  assert.equal(
    recommend(
      makeScenario(["2", "3", "5"], "10", { trueCount: 4 }),
      DEVIATION_RULES,
      true,
    ).action,
    "hit",
  );
  assert.equal(insuranceRecommendation(6, 2, true).take, true);
  assert.equal(insuranceRecommendation(5, 2, true).take, false);
  assert.equal(insuranceRecommendation(6, 2, false).take, false);
});

test("six-deck shuffling preserves all cards and reproduces the same seed", () => {
  const cards = createDeck(111, 6);
  assert.equal(cards.length, 312);
  assert.equal(new Set(cards.map((card) => card.id)).size, 312);
  assert.equal(cards.filter((card) => card.rank === "A").length, 24);
  assert.deepEqual(cards, createDeck(111, 6));
  assert.notDeepEqual(cards, createDeck(112, 6));
});

test("custom hands reject impossible histories and conflicting split settings", () => {
  assert.ok(
    validateScenario(makeScenario(["A", "K", "2", "3"], "6")).includes(
      "A completed hand cannot receive another card.",
    ),
  );
  assert.ok(validateScenario(makeScenario(["10", "10", "5"], "6")).length > 0);
  assert.ok(
    validateScenario(
      makeScenario(["8", "8"], "6", { fromSplit: true, handsCount: 1 }),
    ).length > 0,
  );
  assert.ok(
    validateScenario(
      makeScenario(["A", "8", "2"], "6", {
        fromSplit: true,
        splitAces: true,
        handsCount: 2,
      }),
    ).length > 0,
  );
  assert.ok(
    validateScenario(makeScenario(["A", "8"], "6", { fromSplit: true })).some(
      (error) => error.includes("automatically stand"),
    ),
  );
  assert.ok(
    validateScenario(
      makeScenario(["A", "8", "2"], "6", { fromSplit: true }),
    ).some((error) => error.includes("exactly one")),
  );
  assert.ok(
    validateScenario(
      makeScenario(["A", "8"], "6", { fromSplit: true, splitAces: false }),
    ).some((error) => error.includes("one-card")),
  );
  assert.ok(
    validateScenario(makeScenario(["4", "8"], "6", { handsCount: 2 })).some(
      (error) => error.includes("Every hand"),
    ),
  );
  assert.deepEqual(
    validateScenario(makeScenario(["4", "A", "A"], "6", { fromSplit: true })),
    [],
  );
  assert.equal(
    makeScenario(["4", "A", "A"], "6", { fromSplit: true }).splitAces,
    false,
  );
  assert.equal(
    makeScenario(["A", "8"], "6", { fromSplit: true }).splitAces,
    true,
  );
});

test("focused scenario generation uses the active table rules", () => {
  for (const sampling of ["balanced", "realistic"] as const) {
    for (const rules of [
      DEFAULT_RULES,
      { hitSoft17: true, surrender: true },
      DEVIATION_RULES,
      { hitSoft17: true, surrender: false },
    ]) {
      for (let seed = 0; seed < 100; seed++) {
        const doubled = generateScenario(seed, "double", sampling, [], rules);
        assert.equal(recommend(doubled, rules).action, "double");
        if (rules.surrender) {
          const surrendered = generateScenario(
            seed,
            "surrender",
            sampling,
            [],
            rules,
          );
          assert.equal(recommend(surrendered, rules).action, "surrender");
        }
      }
    }
  }
  assert.throws(
    () => generateScenario(1, "surrender", "balanced", [], DEVIATION_RULES),
    /Enable late surrender/,
  );
  for (let seed = 0; seed < 10; seed++)
    assert.doesNotThrow(() =>
      generateScenario(
        seed,
        "adaptive",
        "balanced",
        ["surrender"],
        DEVIATION_RULES,
      ),
    );
});

test("balanced generation includes reachable split hands after hitting and multiple aces", () => {
  const scenarios = Array.from({ length: 1000 }, (_, seed) =>
    generateScenario(seed, "mixed"),
  );
  assert.ok(
    scenarios.some(
      (scenario) => scenario.fromSplit && scenario.cards.length > 2,
    ),
  );
  assert.ok(
    scenarios.some(
      (scenario) =>
        scenario.fromSplit &&
        scenario.cards.filter((card) => card.rank === "A").length > 1,
    ),
  );
  for (const scenario of scenarios) {
    assert.deepEqual(validateScenario(scenario), []);
    if (scenario.fromSplit)
      assert.notEqual(
        scenario.cards[0].rank,
        "A",
        "completed split aces cannot become a decision puzzle",
      );
  }
});

test("insurance advice uses the same true-count validation and boundary convention", () => {
  assert.equal(insuranceRecommendation(5.9, 2, true).take, false);
  const atBoundary = insuranceRecommendation(6, 2, true);
  assert.equal(atBoundary.take, true);
  assert.equal(atBoundary.index, 3);
  assert.equal(atBoundary.trueCount, 3);
  assert.ok(atBoundary.source.startsWith("https://"));
  assert.throws(() => insuranceRecommendation(3, 0, true), RangeError);
});

test("scenario generation is reproducible, nonterminal and recommendations are legal across rules", () => {
  for (const sampling of ["balanced", "realistic"] as const) {
    for (const topic of [
      "mixed",
      "hard",
      "soft",
      "pairs",
      "double",
      "surrender",
      "adaptive",
      "deviations",
    ]) {
      for (let seed = 1; seed <= 24; seed++) {
        const scenario = generateScenario(seed, topic, sampling, ["soft"]);
        assert.deepEqual(
          scenario,
          generateScenario(seed, topic, sampling, ["soft"]),
        );
        assert.deepEqual(
          validateScenario(scenario),
          [],
          `${sampling} ${topic} seed ${seed}`,
        );
        if (["hard", "soft", "pairs"].includes(topic))
          assert.equal(category(scenario), topic);
        for (const rules of [
          DEFAULT_RULES,
          DEVIATION_RULES,
          { hitSoft17: true, surrender: true },
          { hitSoft17: true, surrender: false },
        ]) {
          assert.ok(
            legalActions(scenario, rules).includes(
              recommend(scenario, rules).action,
            ),
          );
        }
      }
    }
  }
});

test("initial deal counts three exposed cards; the hole card is not leaked", () => {
  const session = startRound(rig(["2", "6", "3", "K"]));
  assert.equal(session.runningCount, 3);
  assert.equal(session.seenIds.length, 3);
  assert.equal(session.nextCard, 4);
  assert.equal(decksRemaining(session), 308 / 52);
  assert.equal(session.round?.dealerRevealed, false);
  assert.deepEqual(
    visibleCards(session).map((card) => card.rank),
    ["2", "6", "3"],
  );
});

test("recommendations cannot change when only the hole card and future cards change", () => {
  const first = startRound(rig(["10", "6", "2", "K", "9", "3"]));
  const second = startRound(rig(["10", "6", "2", "2", "A", "8"]));
  const firstScenario = getActiveScenario(first)!;
  const secondScenario = getActiveScenario(second)!;
  assert.equal(firstScenario.trueCount, secondScenario.trueCount);
  assert.equal(
    recommend(firstScenario).action,
    recommend(secondScenario).action,
  );
  assert.equal(
    recommend(firstScenario, DEVIATION_RULES, true).action,
    recommend(secondScenario, DEVIATION_RULES, true).action,
  );
  assert.deepEqual(
    visibleCards(first).map((card) => card.rank),
    visibleCards(second).map((card) => card.rank),
  );
});

test("dealer peek ends a natural before actions; insurance pays a separate 2:1", () => {
  const peek = startRound(rig(["10", "K", "6", "A"]));
  assert.equal(peek.round?.phase, "complete");
  assert.equal(peek.round?.profit, -1);
  assert.equal(getActiveScenario(peek), null);
  let insured = startRound(rig(["10", "A", "9", "K"]));
  assert.equal(insured.round?.phase, "insurance");
  assert.equal(insured.seenIds.length, 3);
  insured = answerInsurance(insured, true);
  assert.equal(insured.round?.insuranceBet, 0.5);
  assert.equal(insured.round?.insuranceProfit, 1);
  assert.equal(insured.round?.hands[0].profit, -1);
  assert.equal(insured.round?.profit, 0);
  assert.equal(insured.bankroll, 100);
  assert.equal(answerInsurance(insured, true), insured);
});

test("natural pays 3:2, tied naturals push, and insurance loss is included once", () => {
  const natural = startRound(rig(["A", "9", "K", "7"]));
  assert.equal(natural.round?.hands[0].result, "blackjack");
  assert.equal(natural.round?.profit, 1.5);
  assert.equal(natural.nextCard, 4);
  const tied = answerInsurance(startRound(rig(["A", "A", "K", "Q"])), false);
  assert.equal(tied.round?.hands[0].result, "push");
  assert.equal(tied.round?.profit, 0);
  const evenMoney = answerInsurance(
    startRound(rig(["A", "A", "K", "8"])),
    true,
  );
  assert.equal(evenMoney.round?.hands[0].profit, 1.5);
  assert.equal(evenMoney.round?.insuranceProfit, -0.5);
  assert.equal(evenMoney.round?.profit, 1);
});

test("dealer stands on soft 17 under S17 and hits it under H17", () => {
  for (const hitSoft17 of [false, true]) {
    let session = answerInsurance(
      startRound(
        rig(["10", "A", "8", "6", "4"], { hitSoft17, surrender: true }),
      ),
      false,
    );
    session = playAction(session, "stand");
    assert.equal(session.round?.dealer.length, hitSoft17 ? 3 : 2);
    assert.equal(session.round?.profit, hitSoft17 ? -1 : 1);
  }
});

test("split aces each receive one card; two-card split 21 is paid at 1:1", () => {
  const split = playAction(
    startRound(rig(["A", "10", "A", "7", "K", "9"])),
    "split",
  );
  assert.equal(split.round?.phase, "complete");
  assert.equal(split.round?.hands.length, 2);
  assert.deepEqual(
    split.round?.hands.map((item) => item.cards.map((card) => card.rank)),
    [
      ["A", "K"],
      ["A", "9"],
    ],
  );
  assert.deepEqual(
    split.round?.hands.map((item) => item.result),
    ["win", "win"],
  );
  assert.equal(split.round?.profit, 2);
});

test("split hands are dealt in turn, support DAS, and settle individually", () => {
  let session = startRound(rig(["8", "6", "8", "10", "3", "K", "2", "9", "5"]));
  session = playAction(session, "split");
  assert.deepEqual(
    session.round?.hands.map((item) => item.cards.length),
    [2, 1],
  );
  assert.equal(session.nextCard, 5);
  assert.ok(
    legalActions(getActiveScenario(session)!, session.rules).includes("double"),
  );
  session = playAction(session, "double");
  assert.equal(session.round?.activeHand, 1);
  assert.deepEqual(
    session.round?.hands[1].cards.map((card) => card.rank),
    ["8", "2"],
  );
  session = playAction(session, "double");
  assert.deepEqual(
    session.round?.hands.map((item) => item.bet),
    [2, 2],
  );
  assert.deepEqual(
    session.round?.hands.map((item) => item.result),
    ["push", "loss"],
  );
  assert.equal(session.round?.profit, -2);
  assert.equal(session.bankroll, 98);
});

test("resplitting stops at four hands and aces cannot be resplit", () => {
  let session = startRound(rig(["8", "6", "8", "10", "8", "8", "8"]));
  session = playAction(session, "split");
  session = playAction(session, "split");
  session = playAction(session, "split");
  assert.equal(session.round?.hands.length, 4);
  assert.ok(
    !legalActions(getActiveScenario(session)!, session.rules).includes("split"),
  );
  assert.equal(playAction(session, "split"), session);
  const aces = playAction(
    startRound(rig(["A", "10", "A", "7", "A", "A"])),
    "split",
  );
  assert.equal(aces.round?.hands.length, 2);
  assert.equal(aces.round?.phase, "complete");
});

test("doubling bust loses two units and surrender loses half", () => {
  const doubled = playAction(
    startRound(rig(["10", "6", "2", "10", "K"])),
    "double",
  );
  assert.equal(doubled.round?.profit, -2);
  assert.equal(
    doubled.nextCard,
    5,
    "dealer need not draw after every player busts",
  );
  const surrendered = playAction(
    startRound(rig(["10", "9", "6", "8"])),
    "surrender",
  );
  assert.equal(surrendered.round?.hands[0].result, "surrender");
  assert.equal(surrendered.round?.profit, -0.5);
  assert.equal(surrendered.nextCard, 4);
  const pushed = playAction(startRound(rig(["10", "9", "8", "9"])), "stand");
  assert.equal(pushed.round?.profit, 0);
});

test("immutable state and stale decision IDs prevent repeated submissions", () => {
  const original = startRound(rig(["2", "6", "3", "10", "2", "2"]));
  const originalJSON = JSON.stringify(original);
  const id = getActiveScenario(original)!.id;
  const next = playAction(original, "hit", id);
  assert.equal(JSON.stringify(original), originalJSON);
  assert.equal(next.nextCard, 5);
  assert.equal(playAction(next, "hit", id), next);
  assert.equal(startRound(original), original);
  const completed = playAction(next, "stand");
  assert.equal(playAction(completed, "stand"), completed);
  assert.equal(new Set(completed.seenIds).size, completed.seenIds.length);
  assert.equal(
    completed.runningCount,
    visibleCards(completed).reduce((sum, card) => sum + hiLo(card), 0),
  );
});

test("shoe continues across rounds, and cut-card shuffle resets exposure exactly once", () => {
  let session = playAction(
    startRound(rig(["10", "9", "8", "9", "2", "6", "3", "10"])),
    "stand",
  );
  const firstSeen = [...session.seenIds];
  session = startRound(session);
  assert.equal(session.nextCard, 8);
  assert.deepEqual(session.seenIds.slice(0, firstSeen.length), firstSeen);
  assert.equal(session.shuffleNumber, 1);
  const old = createShoe(112, DEFAULT_RULES, 0.25);
  old.nextCard = 78;
  old.seenIds = old.cards.slice(0, 78).map((card) => card.id);
  old.runningCount = 37;
  const shuffled = startRound(old);
  assert.equal(shuffled.shuffleNumber, 2);
  assert.equal(shuffled.nextCard, 4);
  assert.equal(
    shuffled.runningCount,
    visibleCards(shuffled).reduce((sum, card) => sum + hiLo(card), 0),
  );
  assert.ok(!shuffled.seenIds.some((id) => old.seenIds.includes(id)));
});

test("a low-card tail cannot exhaust the shoe during a four-hand round at high penetration", () => {
  // This physical 52-card tail previously exhausted mid-round after three splits
  // and legal hits. A cut card at 85% alone did not protect the round at card 260.
  let session = createShoe(4, { hitSoft17: false, surrender: false }, 0.85);
  const values: Record<string, number> = { A: 1, "2": 2, "3": 3 };
  const low = session.cards
    .filter((card) => card.rank in values)
    .sort((a, b) => values[a.rank] - values[b.rank])
    .slice(0, 52);
  const first: Card[] = (["2", "3", "2", "3", "2", "2", "2"] as Rank[]).map(
    (rank) =>
      low.splice(
        low.findIndex((card) => card.rank === rank),
        1,
      )[0],
  );
  const random = seededRandom(4);
  for (let index = low.length - 1; index > 0; index--) {
    const next = Math.floor(random() * (index + 1));
    [low[index], low[next]] = [low[next], low[index]];
  }
  const tail = [...first, ...low];
  const ids = new Set(tail.map((card) => card.id));
  session.cards = [
    ...session.cards.filter((card) => !ids.has(card.id)),
    ...tail,
  ];
  session.nextCard = 260;
  session.seenIds = session.cards.slice(0, 260).map((card) => card.id);
  session.runningCount = session.cards
    .slice(0, 260)
    .reduce((sum, card) => sum + hiLo(card), 0);
  session = startRound(session);
  assert.equal(
    session.shuffleNumber,
    2,
    "shuffle before starting a round that cannot be guaranteed to finish",
  );
  if (session.round?.phase === "insurance")
    session = answerInsurance(session, false);
  for (let split = 0; split < 3; split++)
    session = playAction(session, "split");
  while (session.round?.phase === "playing")
    session = playAction(session, "hit");
  assert.equal(session.round?.phase, "complete");
  assert.ok(session.nextCard <= 312);
});

test("long seeded sessions preserve accounting, visibility, and finite-shoe invariants", () => {
  for (const hitSoft17 of [false, true]) {
    let session = createShoe(9871, { hitSoft17, surrender: true });
    let profit = 0;
    for (let round = 0; round < 160; round++) {
      session = startRound(session, 1, round);
      if (session.round?.phase === "insurance")
        session = answerInsurance(session, false);
      for (let decision = 0; session.round?.phase === "playing"; decision++) {
        assert.ok(decision < 40, "round must terminate");
        const scenario = getActiveScenario(session)!;
        session = playAction(
          session,
          recommend(scenario, session.rules).action,
          scenario.id,
        );
      }
      assert.equal(session.round?.phase, "complete");
      profit += session.round!.profit;
      assert.equal(session.bankroll, 100 + profit);
      assert.equal(session.rounds, round + 1);
      assert.equal(
        session.seenIds.length,
        session.nextCard,
        "all cards are exposed at round completion",
      );
      assert.equal(
        session.runningCount,
        visibleCards(session).reduce((sum, card) => sum + hiLo(card), 0),
      );
      assert.ok(session.nextCard <= 312);
      assert.ok(session.round!.hands.length <= 4);
    }
    assert.ok(session.shuffleNumber >= 3);
  }
});
